from dataclasses import dataclass, field
from pathlib import Path

from src.domain.cluster import Cluster
from src.domain.execution import Execution


@dataclass
class ExecutionPlan:
    """
    Resolved execution plan generated by the planner.

    Unlike Execution, which represents what the engineer requested,
    ExecutionPlan represents what the application will actually execute.
    """

    execution: Execution

    clusters: list[Cluster] = field(default_factory=list)

    collectors: list[str] = field(default_factory=list)

    snapshot_directory: Path | None = None

    report_directory: Path | None = None

    comparison_enabled: bool = False

    dashboard_enabled: bool = True

    worker_count: int = 15